@OEMEVWarrantyManagementSystem.GraphQl.WebAPI.HienNPQ_HostAddress = http://localhost:5266

GET {{OEMEVWarrantyManagementSystem.GraphQl.WebAPI.HienNPQ_HostAddress}}/weatherforecast/
Accept: application/json

###
