// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OEMEVWarrantyManagementSystem.BlazorWebApp.HienNPQ.Models;

public partial class SupportInfoHienNpq
{
    public int SupportInfoHienNpqid { get; set; }

    public string LicensePlate { get; set; }

    public string Color { get; set; }

    public string Notes { get; set; }

    public virtual ICollection<BookingHienNpq> BookingHienNpqs { get; set; } = new List<BookingHienNpq>();
}