// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OEMEVWarrantyManagementSystem.Repositories.HienNPQ.Models;

public partial class BookingHienNpq
{
    public int BookingHienNpqid { get; set; }

    public int AccountId { get; set; }

    public string StationName { get; set; }

    public string VehicleType { get; set; }

    public int BatteryCapacity { get; set; }

    public decimal PricePerHour { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool IsPreBooked { get; set; }

    public string Status { get; set; }

    public int? SupportInfoHienNpqid { get; set; }

    public virtual SupportInfoHienNpq SupportInfoHienNpq { get; set; }
}